[profile.default]
evm_version = "shanghai"       # See https://www.evmdiff.com/features?name=PUSH0&kind=opcode
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
test = "test"
cache_path = "cache_forge"
optimizer = true
optimizer_runs = 10_000
solc_version = "0.8.21"
build_info = true
extra_output = ["storageLayout"]

[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
# https://github.com/foundry-rs/forge-std/blob/ff4bf7db008d096ea5a657f2c20516182252a3ed/src/StdCheats.sol#L255-L271
mainnet = "${MAINNET_RPC_URL}"
holesky = "${HOLESKY_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
holesky = { key = "${ETHERSCAN_API_KEY}" }
